stages:
  - build
  - release

before_script:
  - echo $GOPATH
  - ln -s /builds /go/src/github.com
  - ln -s /go/src/github.com/containerd /go/src/github.com/docker
  - cd /go/src/github.com/containerd/containerd

compile:
  image: golang:1.8.1
  stage: build
  variables:
    CGO_ENABLED: '0'
    GOOS: linux
  script:
    - apt-get update ; apt-get install -y
        unzip
        sudo
        btrfs-tools
        libseccomp-dev
        libapparmor-dev
        libnl-3-dev
        libnet-dev
        protobuf-c-compiler
        protobuf-compiler
        python-minimal
        libcap-dev
        libaio-dev
        libprotobuf-c0-dev
        libprotobuf-dev
    - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip -O /tmp/protoc-3.1.0-linux-x86_64.zip
    - unzip -o -d /tmp/protobuf /tmp/protoc-3.1.0-linux-x86_64.zip
    - export PATH=/tmp/protobuf/bin:$PATH
    - go get -u github.com/vbatts/git-validation
    - sudo wget https://github.com/crosbymichael/runc/releases/download/ctd-1/runc -O /bin/runc; sudo chmod +x /bin/runc
    - wget https://github.com/xemul/criu/archive/v3.0.tar.gz -O /tmp/criu.tar.gz
    - tar -C /tmp/ -zxf /tmp/criu.tar.gz
    - cd /tmp/criu-3.0
    - sudo make install-criu
    - cd /go/src/github.com/containerd/containerd
    - make -j $(getconf _NPROCESSORS_ONLN)
    - mv bin/* .
    - echo CONTAINERD_BINARY=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/file/containerd | tee release.env
    - echo CONTAINERD_SHIM_BINARY=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/file/containerd | tee -a release.env
    - echo CONTAINERD_CTR_BINARY=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/file/containerd | tee -a release.env

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
    paths:
      - containerd
      - containerd-shim
      - ctr
      - release.env


release:
  stage: release
  image: golang:1.8.1
  script:
    - cat release.env
  dependencies:
    - compile
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
    paths:
      - release.env
